sonar.projectKey=navir-ufam
sonar.organization=navir-ufam
sonar.projectName=NAVIR-Web

sonar.sources=src/backend/src,src/frontend/src

sonar.tests=src/backend/test,src/backend/src,src/frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.js,**/coverage/**,**/public/**,**/*.svg,**/*.png,**/components/ui/**,**/components/ComponentShowcase.tsx

sonar.coverage.exclusions=**/components/ui/**,**/components/ComponentShowcase.tsx,**/routes/**,**/hooks/**,**/lib/utils.ts,**/app/App.tsx,**/main.tsx,**/index.ts,**/index.tsx,**/*.svg,**/*.png,**/mocks/**,**/pages/**

sonar.typescript.lcov.reportPaths=src/backend/coverage/lcov.info,src/frontend/coverage/lcov.info

sonar.typescript.tsconfigPaths=src/backend/tsconfig.json,src/frontend/tsconfig.json